# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
      npm run build
    displayName: 'Build React App'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'       # This is React's output folder
      ArtifactName: 'react-portfolio'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
